CI: Add golang format checking. (#5)

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -29,6 +29,10 @@ jobs:
       run: |
         go get -v -t -d ./...
 
+    - name: Format Check
+      run: |
+        if [ $(gofmt -l -s . | wc -l) -ne 0 ]; then echo "gofmt failed"; exit 1; fi
+
     - name: Build
       run: |
         go build -v ./cmd/server/main.go
